[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$ServerUrl,
  [Parameter(Mandatory = $true)][int]$ServerId,
  [Parameter(Mandatory = $true)][string]$SecretKey,

  [string]$Repo = "EnderKC/BetterMonitor",
  [string]$Version = "latest",
  [string]$Channel = "stable",

  [string]$ServiceName = "BetterMonitorAgent",
  [string]$AssetName = "",
  [string]$DownloadUrl = "",
  [string]$Sha256 = "",
  [switch]$SkipVerify,

  [string]$InstallDir = "",
  [switch]$UseScheduledTask,
  [string]$GitHubToken = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Info([string]$Message) { Write-Host "[install] $Message" }
function Write-Warn([string]$Message) { Write-Warning $Message }
function Fail([string]$Message) { throw $Message }

function Is-Admin {
  $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Arch {
  $arch = $env:PROCESSOR_ARCHITECTURE
  switch ($arch) {
    "AMD64" { return "amd64" }
    "ARM64" { return "arm64" }
    "x86"   { return "386" }
    default { return "amd64" }
  }
}

function Normalize-Tag([string]$v) {
  $v = $v.Trim()
  if ($v -eq "" -or $v -eq "latest") { return "latest" }
  if ($v.StartsWith("v")) { return $v }
  return "v$($v)"
}

function Invoke-GitHubApi([string]$Uri) {
  $headers = @{
    "Accept" = "application/vnd.github+json"
    "User-Agent" = "better-monitor-agent-installer"
  }
  if ($GitHubToken -ne "") {
    $headers["Authorization"] = "Bearer $GitHubToken"
  }
  return Invoke-RestMethod -Uri $Uri -Headers $headers -Method Get
}

function Resolve-Release([string]$repo, [string]$tag) {
  if ($tag -eq "latest") {
    return Invoke-GitHubApi -Uri "https://api.github.com/repos/$repo/releases/latest"
  }
  return Invoke-GitHubApi -Uri "https://api.github.com/repos/$repo/releases/tags/$tag"
}

function Resolve-DownloadUrl([object]$release, [string]$assetName) {
  foreach ($a in $release.assets) {
    if ($a.name -eq $assetName) { return $a.browser_download_url }
  }
  return ""
}

function Download-File([string]$Url, [string]$OutFile) {
  Write-Info "Downloading: $Url"
  $headers = @{ "User-Agent" = "better-monitor-agent-installer" }
  if ($GitHubToken -ne "") {
    $headers["Authorization"] = "Bearer $GitHubToken"
  }
  Invoke-WebRequest -Uri $Url -OutFile $OutFile -Headers $headers -UseBasicParsing
}

function Ensure-Directory([string]$Path) {
  if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Path $Path | Out-Null }
}

function Write-EnvFile([string]$EnvPath) {
  @"
# Generated by install-agent.ps1
SERVER_URL="$ServerUrl"
PANEL_URL="$ServerUrl"
SERVER_ID="$ServerId"
SECRET_KEY="$SecretKey"
CHANNEL="$Channel"
"@ | Set-Content -Path $EnvPath -Encoding UTF8
}

function Install-ScheduledTask([string]$AgentExe, [string]$WorkDir) {
  Write-Info "Installing scheduled task: $ServiceName"

  $action = New-ScheduledTaskAction -Execute $AgentExe -WorkingDirectory $WorkDir

  if (Is-Admin) {
    $trigger = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName $ServiceName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
    Start-ScheduledTask -TaskName $ServiceName
    return
  }

  $trigger = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable
  Register-ScheduledTask -TaskName $ServiceName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
  Start-ScheduledTask -TaskName $ServiceName
}

# TLS hardening for older Windows/PowerShell
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}

$arch = Get-Arch
$tag = Normalize-Tag $Version

if ($InstallDir -eq "") {
  if (Is-Admin) {
    $InstallDir = Join-Path $env:ProgramFiles "BetterMonitor\Agent"
  } else {
    $InstallDir = Join-Path $env:LOCALAPPDATA "BetterMonitor\Agent"
  }
}

$workDir = $InstallDir
$agentExe = Join-Path $InstallDir "better-monitor-agent.exe"
$envFile = Join-Path $InstallDir "agent.env"

Ensure-Directory $InstallDir

if ($AssetName -eq "") {
  $AssetName = "better-monitor-agent-windows-$arch.exe"
}

$downloadUrl = $DownloadUrl
$release = $null

if ($downloadUrl -eq "") {
  $release = Resolve-Release -repo $Repo -tag $tag
  $downloadUrl = Resolve-DownloadUrl -release $release -assetName $AssetName
  if ($downloadUrl -eq "") {
    Fail "Asset not found in release: $AssetName (repo=$Repo tag=$tag)"
  }
}

$tmpExe = Join-Path ([System.IO.Path]::GetTempPath()) ("bm-agent-" + [Guid]::NewGuid().ToString("n") + ".exe")
Download-File -Url $downloadUrl -OutFile $tmpExe

if (-not $SkipVerify) {
  Write-Warn "SHA256 verification not implemented in this version. Use -SkipVerify to continue."
}

Move-Item -Force $tmpExe $agentExe

Write-EnvFile -EnvPath $envFile

Write-Info "Installed: $agentExe"
Write-Info "Config: $envFile"

if ($UseScheduledTask) {
  Install-ScheduledTask -AgentExe $agentExe -WorkDir $workDir
  Write-Info "Done (scheduled task)"
  exit 0
}

if (-not (Is-Admin)) {
  Write-Warn "Not running as Administrator; falling back to scheduled task."
  Install-ScheduledTask -AgentExe $agentExe -WorkDir $workDir
  Write-Info "Done (scheduled task)"
  exit 0
}

Write-Warn "NSSM service installation not implemented. Using scheduled task."
Install-ScheduledTask -AgentExe $agentExe -WorkDir $workDir
Write-Info "Done (scheduled task)"
