enable_cpu_monitor: true
enable_disk_monitor: true
enable_mem_monitor: true
enable_network_monitor: true
heartbeat_interval: 10s
log_file: ./logs/agent.log
log_level: debug
monitor_interval: 10s
update_repo: EnderKC/BetterMonitor
update_channel: stable
update_mirror: ""
register_token: ""
secret_key: ""
server_id: 0
server_url: 127.0.0.1:8080
